"""
Report generation: the Section 63(4) certificate and the narrative case
report, both returned as the PDF itself.

Both generator functions in :mod:`pramaan.report` refuse to overwrite an
existing ``dest_path`` — the right behavior for a caller writing into a
real, permanent location, but not something an HTTP response needs to
worry about. Each request here builds its PDF into a fresh temporary
directory, reads the bytes back, and returns them directly; nothing
generated by a report request is left on disk after the response is
sent.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Response

from pramaan.api.dependencies import get_case
from pramaan.api.schemas import (
    CaseReportGenerateRequest,
    CertificateGenerateRequest,
    CertificatePartARequest,
    CertificatePartBRequest,
    DeviceDetailsRequest,
    HashDeclarationRequest,
)
from pramaan.case.store import Case
from pramaan.report.case_report import CaseReportError, GapAnalysisWindow, generate_case_report_pdf
from pramaan.report.certificate import (
    Certificate,
    CertificateError,
    CertificatePartA,
    CertificatePartB,
    DeviceDetails,
    HashDeclaration,
    generate_certificate_pdf,
)

router = APIRouter(tags=["reports"])

_PDF_MEDIA_TYPE = "application/pdf"


def _device_from_request(body: DeviceDetailsRequest) -> DeviceDetails:
    return DeviceDetails(
        device_type=body.device_type, make_and_model=body.make_and_model,
        serial_number=body.serial_number, identifier=body.identifier,
        other_device_type=body.other_device_type,
    )


def _hash_from_request(body: HashDeclarationRequest) -> HashDeclaration:
    return HashDeclaration(
        algorithm=body.algorithm, value=body.value, other_algorithm_name=body.other_algorithm_name,
    )


def _part_a_from_request(body: CertificatePartARequest) -> CertificatePartA:
    return CertificatePartA(
        custodian_name=body.custodian_name, custodian_address=body.custodian_address,
        device=_device_from_request(body.device),
        lawful_control_declared=body.lawful_control_declared,
        functioning_properly_declared=body.functioning_properly_declared,
        hash=_hash_from_request(body.hash), place=body.place, date=body.date, time_ist=body.time_ist,
    )


def _part_b_from_request(body: CertificatePartBRequest) -> CertificatePartB:
    return CertificatePartB(
        expert_name=body.expert_name, expert_designation=body.expert_designation,
        device=_device_from_request(body.device), hash=_hash_from_request(body.hash),
        technical_statement=body.technical_statement, place=body.place, date=body.date,
        time_ist=body.time_ist,
    )


@router.post("/cases/{case_id}/reports/certificate")
def generate_certificate(
    body: CertificateGenerateRequest, case: Case = Depends(get_case),
) -> Response:
    case_id = case.info().case_id
    try:
        certificate = Certificate(
            case_id=case_id,
            part_a=_part_a_from_request(body.part_a),
            part_b=_part_b_from_request(body.part_b),
        )
    except CertificateError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    with tempfile.TemporaryDirectory() as tmp_dir:
        dest = Path(tmp_dir) / "certificate.pdf"
        generate_certificate_pdf(certificate, dest)
        pdf_bytes = dest.read_bytes()

    return Response(
        content=pdf_bytes, media_type=_PDF_MEDIA_TYPE,
        headers={"Content-Disposition": f'attachment; filename="{case_id}_certificate.pdf"'},
    )


@router.post("/cases/{case_id}/reports/case-report")
def generate_case_report(
    body: CaseReportGenerateRequest, case: Case = Depends(get_case),
) -> Response:
    case_id = case.info().case_id
    window = None
    if body.gap_analysis_window is not None:
        try:
            window = GapAnalysisWindow(
                start=body.gap_analysis_window.start, end=body.gap_analysis_window.end,
            )
        except CaseReportError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    with tempfile.TemporaryDirectory() as tmp_dir:
        dest = Path(tmp_dir) / "case_report.pdf"
        generate_case_report_pdf(case, dest, gap_analysis_window=window)
        pdf_bytes = dest.read_bytes()

    return Response(
        content=pdf_bytes, media_type=_PDF_MEDIA_TYPE,
        headers={"Content-Disposition": f'attachment; filename="{case_id}_report.pdf"'},
    )
