"""
The narrative case report: a single PDF composing everything a
:class:`pramaan.case.store.Case` has accumulated — evidence intake,
recovered footage, the multi-channel timeline, examiner findings, and the
audit ledger's own integrity verification — into the document an
examiner hands to a reviewing officer or a court alongside the case's
:mod:`pramaan.export` bundle and its :mod:`pramaan.report.certificate`.

This module reads a :class:`~pramaan.case.store.Case` and renders exactly
what is in it. It states counts, hashes, and verification results it can
compute from the case store itself; it never infers a finding, a device
category, or a conclusion the case data does not already contain. Where
information a thorough report would want (a per-channel gap analysis)
needs a caller-supplied parameter this module cannot derive on its own —
the *expected recording window* — the corresponding section is included
only when that parameter is given, and is stated as skipped, not silently
omitted, when it isn't.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from pramaan.case.store import Case, ClipRow, EvidenceItem, Finding
from pramaan.report._styles import build_report_styles
from pramaan.timeline.gaps import Anomaly, find_anomalies
from pramaan.timeline.model import SegmentKind

_DISCLAIMER_TEXT = (
    "This report was generated by Pramaan directly from the contents of the "
    "named case store at the time stated above. Every count, hash, and "
    "verification result in this document is computed from that case's own "
    "recorded evidence items, clips, findings, and audit ledger -- it "
    "reflects what has been entered into the case, not an independent "
    "judgement of what occurred on the source device. This report is not "
    "the Section 63(4) certificate required for admissibility; see "
    "pramaan.report.certificate for that document."
)

_KIND_LABELS: dict[str, str] = {
    SegmentKind.RECORDED.value: "Recorded (intact index)",
    SegmentKind.RECOVERED.value: "Recovered (carved)",
    SegmentKind.CORRUPT.value: "Corrupt",
    SegmentKind.UNKNOWN.value: "Unknown",
}

_ANOMALY_LABELS: dict[str, str] = {
    "recovered_from_unallocated": "Recovered from unallocated space",
    "expected_overwrite": "Expected overwrite (ring-buffer edge)",
    "sequence_discontinuity": "Sequence discontinuity",
    "unexplained_gap": "Unexplained gap",
}


class CaseReportError(Exception):
    """Raised for a case-report usage error — not a PDF-rendering
    failure, a genuine misuse this layer itself can detect."""


@dataclass(frozen=True)
class GapAnalysisWindow:
    """The wall-clock window the report's gap analysis should treat as
    the recording's expected coverage. There is no way to derive this
    from a case store alone -- a recorder's actual retention window is
    outside knowledge, so a caller (an examiner, working from the
    device's known deployment period) must supply it explicitly."""

    start: datetime
    end: datetime

    def __post_init__(self) -> None:
        if self.end <= self.start:
            raise CaseReportError("GapAnalysisWindow end must be after start")


def _table(rows: list[list[str]], styles: dict[str, ParagraphStyle], col_widths: list[float]) -> Table:
    wrapped = [[Paragraph(f"<b>{cell}</b>", styles["body"]) for cell in rows[0]]]
    for row in rows[1:]:
        wrapped.append([Paragraph(cell, styles["body"]) for cell in row])
    table = Table(wrapped, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return table


def _case_summary_story(case: Case, styles: dict[str, ParagraphStyle]) -> list:
    info = case.info()
    return [
        Paragraph(f"<b>Case ID:</b> {info.case_id}", styles["body"]),
        Paragraph(f"<b>Title:</b> {info.title}", styles["body"]),
        Paragraph(f"<b>Investigating agency:</b> {info.investigating_agency}", styles["body"]),
        Paragraph(f"<b>Examiner:</b> {info.examiner_name}", styles["body"]),
        Paragraph(f"<b>Case created:</b> {info.created_at}", styles["body"]),
    ]


def _evidence_items_story(items: list[EvidenceItem], styles: dict[str, ParagraphStyle]) -> list:
    """One block per evidence item, not a multi-column table row.

    A SHA-256 hash is 64 hex characters -- fine as its own full-width
    monospace line (the pattern :mod:`pramaan.report.certificate` already
    uses), but forced to wrap mid-string, with no separator, the moment
    it is squeezed into a narrow table cell. This report never truncates
    or reflows a hash for the sake of a compact grid.
    """
    if not items:
        return [Paragraph("No evidence items have been recorded in this case.", styles["body"])]
    story: list = []
    for item in items:
        device = " / ".join(p for p in (item.device_type, item.make_model) if p) or "N/A"
        if item.write_block_attestation is None:
            wb = "Not checked"
        elif item.write_block_attestation.get("write_open_refused"):
            wb = "Write-open refused"
        else:
            wb = "Write-open permitted"
        story.append(Paragraph(f"<b>#{item.id}: {item.description}</b>", styles["body"]))
        story.append(Paragraph(
            f"Device: {device} &nbsp;&nbsp; Size: {item.size_bytes} bytes &nbsp;&nbsp; "
            f"Write-block check: {wb} &nbsp;&nbsp; Acquired: {item.acquired_at}",
            styles["body"],
        ))
        story.append(Paragraph(f"SHA-256: <font name='Courier'>{item.sha256}</font>", styles["mono"]))
        story.append(Spacer(1, 3 * mm))
    return story


def _clip_kind_counts(clips: list[ClipRow]) -> dict[int, dict[str, int]]:
    counts: dict[int, dict[str, int]] = {}
    for clip in clips:
        per_channel = counts.setdefault(clip.channel, {})
        per_channel[clip.kind] = per_channel.get(clip.kind, 0) + 1
    return counts


def _coverage_summary_story(clips: list[ClipRow], styles: dict[str, ParagraphStyle]) -> list:
    if not clips:
        return [Paragraph("No clips have been recorded in this case.", styles["body"])]
    counts = _clip_kind_counts(clips)
    header = ["Channel", *_KIND_LABELS.values(), "Total"]
    rows = [header]
    for channel in sorted(counts):
        per_kind = counts[channel]
        row = [str(channel)]
        total = 0
        for kind in _KIND_LABELS:
            n = per_kind.get(kind, 0)
            total += n
            row.append(str(n))
        row.append(str(total))
        rows.append(row)
    col_widths = [18 * mm] + [28 * mm] * len(_KIND_LABELS) + [16 * mm]
    return [_table(rows, styles, col_widths)]


def _clip_exhibit_story(clips: list[ClipRow], styles: dict[str, ParagraphStyle]) -> list:
    """One block per clip, for the same reason :func:`_evidence_items_story`
    is blocks rather than table rows: a clip's SHA-256 (when it has one --
    an index-walk clip generally doesn't, since its provenance is the
    index entry itself, not a carved payload) needs a full-width line."""
    if not clips:
        return [Paragraph("No clips to list.", styles["body"])]
    story: list = []
    for clip in clips:
        kind_label = _KIND_LABELS.get(clip.kind, clip.kind)
        start = clip.start_time or "unknown"
        end = clip.end_time or "unknown"
        frames = str(clip.frame_count) if clip.frame_count is not None else "N/A"
        story.append(Paragraph(f"<b>Channel {clip.channel}, clip #{clip.id}</b> ({kind_label})", styles["body"]))
        story.append(Paragraph(
            f"Start: {start} &nbsp;&nbsp; End: {end} &nbsp;&nbsp; Frames: {frames}",
            styles["body"],
        ))
        story.append(Paragraph(
            f"SHA-256: <font name='Courier'>{clip.sha256 or 'N/A'}</font>", styles["mono"],
        ))
        if clip.note:
            story.append(Paragraph(f"Note: {clip.note}", styles["small"]))
        story.append(Spacer(1, 3 * mm))
    return story


def _findings_story(findings: list[Finding], styles: dict[str, ParagraphStyle]) -> list:
    if not findings:
        return [Paragraph("No findings have been recorded in this case.", styles["body"])]
    story: list = []
    for finding in findings:
        clip_ref = f"clip {finding.clip_id}" if finding.clip_id is not None else "no associated clip"
        story.append(Paragraph(
            f"<b>[{finding.category}]</b> {finding.description} "
            f"<i>(recorded by {finding.author} at {finding.created_at}, {clip_ref})</i>",
            styles["body"],
        ))
        story.append(Spacer(1, 2 * mm))
    return story


def _anomaly_story(
    case: Case, window: GapAnalysisWindow, styles: dict[str, ParagraphStyle]
) -> list:
    timeline = case.build_timeline()
    if not timeline.channels:
        return [Paragraph(
            "No timed clips are available to analyze -- gap analysis requires "
            "at least one clip with a known start and end time.", styles["body"],
        )]
    all_anomalies: list[tuple[int, Anomaly]] = []
    for channel in timeline.channels:
        for anomaly in find_anomalies(timeline, channel, window.start, window.end):
            all_anomalies.append((channel, anomaly))
    if not all_anomalies:
        return [Paragraph(
            f"No anomalies were found on any channel within the analyzed "
            f"window ({window.start.isoformat()} to {window.end.isoformat()}).",
            styles["body"],
        )]
    story: list = [Paragraph(
        f"Analyzed window: {window.start.isoformat()} to {window.end.isoformat()}.",
        styles["small"],
    ), Spacer(1, 2 * mm)]
    for channel, anomaly in all_anomalies:
        label = _ANOMALY_LABELS.get(anomaly.category.value, anomaly.category.value)
        rationale = " ".join(anomaly.rationale)
        story.append(Paragraph(
            f"<b>Channel {channel} -- {label}</b> "
            f"({anomaly.start.isoformat()} to {anomaly.end.isoformat()}): {rationale}",
            styles["body"],
        ))
        story.append(Spacer(1, 2 * mm))
    return story


def _integrity_story(case: Case, styles: dict[str, ParagraphStyle]) -> list:
    verification = case.verify_integrity()
    ledger = case.ledger
    status = "VALID -- no break detected" if verification.valid else "BROKEN -- see detail below"
    story = [
        Paragraph(f"<b>Ledger entries:</b> {len(ledger.entries)}", styles["body"]),
        Paragraph(f"<b>Head hash:</b> <font name='Courier'>{ledger.head_hash}</font>", styles["mono"]),
        Paragraph(f"<b>Chain verification:</b> {status}", styles["body"]),
    ]
    if not verification.valid:
        story.append(Paragraph(
            f"<b>Break at entry index:</b> {verification.break_at_index} -- "
            f"<b>reason:</b> {verification.reason}",
            styles["body"],
        ))
    return story


def generate_case_report_pdf(
    case: Case,
    dest_path: str | Path,
    *,
    gap_analysis_window: GapAnalysisWindow | None = None,
    generated_at: datetime | None = None,
) -> Path:
    """Render the full narrative report for ``case`` at ``dest_path``.

    Raises :class:`CaseReportError` if ``dest_path`` already exists, for
    the same reason :func:`pramaan.report.certificate.generate_certificate_pdf`
    does: this is an evidentiary document, and silently overwriting one
    that already exists is not this function's call to make.

    ``gap_analysis_window`` is optional because there is no way to derive
    a recorder's expected coverage window from the case store alone --
    when omitted, the report says so explicitly rather than guessing one.
    """
    dest_path = Path(dest_path)
    if dest_path.exists():
        raise CaseReportError(f"{dest_path} already exists")

    generated = generated_at if generated_at is not None else datetime.now(UTC)
    styles = build_report_styles()
    doc = SimpleDocTemplate(
        str(dest_path), pagesize=A4,
        topMargin=20 * mm, bottomMargin=18 * mm, leftMargin=18 * mm, rightMargin=18 * mm,
    )

    evidence_items = case.list_evidence_items()
    clips = case.list_clips()
    findings = case.list_findings()

    story: list = [
        Paragraph("Case Report", styles["title"]),
        Paragraph(f"Generated {generated.isoformat()}", styles["subtitle"]),
        Spacer(1, 5 * mm),
        Paragraph("Case Summary", styles["heading"]),
        *_case_summary_story(case, styles),
        Paragraph("Evidence Items", styles["heading"]),
        *_evidence_items_story(evidence_items, styles),
        Paragraph("Recovery Coverage Summary", styles["heading"]),
        *_coverage_summary_story(clips, styles),
        PageBreak(),
        Paragraph("Clip Exhibit List", styles["heading"]),
        *_clip_exhibit_story(clips, styles),
        PageBreak(),
        Paragraph("Examiner Findings", styles["heading"]),
        *_findings_story(findings, styles),
        Paragraph("Timeline Anomaly Analysis", styles["heading"]),
    ]

    if gap_analysis_window is not None:
        story.extend(_anomaly_story(case, gap_analysis_window, styles))
    else:
        story.append(Paragraph(
            "Skipped -- no expected recording window was supplied for this "
            "report. Gap analysis requires an examiner-supplied window of "
            "expected coverage, which cannot be derived from the case store "
            "alone.", styles["body"],
        ))

    story.append(Paragraph("Audit Ledger Integrity", styles["heading"]))
    story.extend(_integrity_story(case, styles))
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(_DISCLAIMER_TEXT, styles["small"]))

    doc.build(story)
    return dest_path
