"""
The Bharatiya Sakshya Adhiniyam 2023 Section 63(4) certificate.

Section 63 (replacing Indian Evidence Act Section 65B) makes electronic
records admissible only when accompanied by a certificate in the form the
Adhiniyam's own Schedule prescribes. Confirmed from that Schedule (see
``docs/sources.md`` for the exact source and its confidence level): the
certificate is split into **Part A**, completed by the person in charge of
the device, and **Part B**, completed by a technical expert; both name a
hash value and algorithm (SHA1, SHA256, MD5, or Other); and the device
category field explicitly lists **DVR** alongside Computer, Mobile, and
Flash Drive — this is not a generic export report retrofitted with legal
language, it is the actual prescribed form.

No commercial or open-source DVR forensic tool surveyed during this
project's research generates this certificate at all; every one of them
stops at a vendor-neutral export report. This module is a direct,
literal answer to a real, cited, unmet requirement — not a nice-to-have
bolted on afterward.

**This module renders what a human examiner attests to; it never attests
to anything on its own.** Every declaration here (lawful control, proper
functioning, the technical statement) is free text supplied by the
caller — an actual custodian's and an actual expert's own words — not
generated or inferred by Pramaan. The one thing this project cannot do is
turn a case's hashes and metadata into a legal attestation by itself.

The exact Schedule wording used here was confirmed from a secondary bare-act
reproduction, not the primary indiacode.nic.in text (which blocked automated
fetch during this project's research). Verify the live field labels against
the primary bare act before this certificate is used in an actual filing —
see ``docs/sources.md``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

#: Device categories named in the Schedule, plus the "Other" catch-all it
#: itself provides for — DVR is not an approximation of "Computer" here,
#: it is a category the form names explicitly.
DEVICE_TYPES: tuple[str, ...] = (
    "Computer", "DVR", "NVR", "Mobile Phone", "Flash Drive", "Hard Disk", "Other",
)

#: The Schedule's own hash-algorithm checkboxes, verbatim.
HASH_ALGORITHMS: tuple[str, ...] = ("SHA1", "SHA256", "MD5", "Other")

_DISCLAIMER_TEXT = (
    "This certificate was generated by Pramaan from the fields supplied by the "
    "persons named above. It reproduces the field structure of the Bharatiya "
    "Sakshya Adhiniyam, 2023 Schedule as confirmed against a secondary bare-act "
    "reproduction; verify current wording and formatting against the primary "
    "bare act (indiacode.nic.in) before relying on this document in a filing. "
    "Pramaan attests to nothing in this certificate itself -- every declaration "
    "above was supplied by the named custodian or expert."
)


class CertificateError(Exception):
    """Raised for invalid certificate data — a value that doesn't belong
    on a Section 63(4) certificate at all, not a PDF-rendering failure."""


@dataclass(frozen=True)
class DeviceDetails:
    device_type: str
    make_and_model: str
    serial_number: str | None = None
    identifier: str | None = None
    other_device_type: str | None = None

    def __post_init__(self) -> None:
        if self.device_type not in DEVICE_TYPES:
            raise CertificateError(f"device_type must be one of {DEVICE_TYPES}")
        if self.device_type == "Other" and not self.other_device_type:
            raise CertificateError("device_type 'Other' requires other_device_type")

    @property
    def display_type(self) -> str:
        if self.device_type == "Other":
            # __post_init__ guarantees other_device_type is set whenever
            # device_type is "Other" -- this assertion documents that
            # invariant to mypy rather than silencing it with a cast.
            assert self.other_device_type is not None
            return self.other_device_type
        return self.device_type


@dataclass(frozen=True)
class HashDeclaration:
    algorithm: str
    value: str
    other_algorithm_name: str | None = None

    def __post_init__(self) -> None:
        if self.algorithm not in HASH_ALGORITHMS:
            raise CertificateError(f"algorithm must be one of {HASH_ALGORITHMS}")
        if self.algorithm == "Other" and not self.other_algorithm_name:
            raise CertificateError("algorithm 'Other' requires other_algorithm_name")
        if not self.value.strip():
            raise CertificateError("hash value must not be empty")

    @property
    def display_algorithm(self) -> str:
        if self.algorithm == "Other":
            # __post_init__ guarantees other_algorithm_name is set whenever
            # algorithm is "Other" -- this assertion documents that
            # invariant to mypy rather than silencing it with a cast.
            assert self.other_algorithm_name is not None
            return self.other_algorithm_name
        return self.algorithm


@dataclass(frozen=True)
class CertificatePartA:
    """Completed by the person in charge of the device at the material time."""

    custodian_name: str
    custodian_address: str
    device: DeviceDetails
    lawful_control_declared: bool
    functioning_properly_declared: bool
    hash: HashDeclaration
    place: str
    date: str
    time_ist: str

    def __post_init__(self) -> None:
        if not self.lawful_control_declared or not self.functioning_properly_declared:
            raise CertificateError(
                "Part A requires both the lawful-control and proper-functioning "
                "declarations -- a certificate cannot be generated on the "
                "custodian's behalf without them; obtain the actual declaration "
                "before constructing this object, not after"
            )


@dataclass(frozen=True)
class CertificatePartB:
    """Completed by a technical expert."""

    expert_name: str
    expert_designation: str
    device: DeviceDetails
    hash: HashDeclaration
    technical_statement: str
    place: str
    date: str
    time_ist: str

    def __post_init__(self) -> None:
        if not self.technical_statement.strip():
            raise CertificateError(
                "Part B requires the expert's own technical statement -- this "
                "is the expert's attestation, not text Pramaan can supply"
            )


@dataclass(frozen=True)
class Certificate:
    case_id: str
    part_a: CertificatePartA
    part_b: CertificatePartB


def _hash_checkboxes(selected: str) -> str:
    boxes = []
    for algo in HASH_ALGORITHMS:
        mark = "X" if algo == selected else " "
        boxes.append(f"[{mark}] {algo}")
    return "    ".join(boxes)


def _device_table(device: DeviceDetails, styles: dict[str, ParagraphStyle]) -> Table:
    rows = [
        ["Device type", device.display_type],
        ["Make and model", device.make_and_model],
        ["Serial number", device.serial_number or "N/A"],
        ["Identifier (IMEI/UID/MAC/Cloud ID)", device.identifier or "N/A"],
    ]
    table = Table(
        [[Paragraph(f"<b>{label}</b>", styles["body"]), Paragraph(value, styles["body"])] for label, value in rows],
        colWidths=[65 * mm, 100 * mm],
    )
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return table


def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("CertTitle", parent=base["Title"], fontSize=15, spaceAfter=2 * mm),
        "subtitle": ParagraphStyle("CertSubtitle", parent=base["Heading3"], fontSize=11, textColor=colors.grey),
        "heading": ParagraphStyle("PartHeading", parent=base["Heading2"], fontSize=13, spaceBefore=6 * mm, spaceAfter=3 * mm),
        "body": ParagraphStyle("CertBody", parent=base["BodyText"], fontSize=10, leading=14),
        "mono": ParagraphStyle("CertMono", parent=base["BodyText"], fontName="Courier", fontSize=9, leading=13),
        "small": ParagraphStyle("CertSmall", parent=base["BodyText"], fontSize=8, textColor=colors.grey, leading=11),
    }


def _part_a_story(part: CertificatePartA, styles: dict[str, ParagraphStyle]) -> list:
    return [
        Paragraph(f"<b>Name:</b> {part.custodian_name}", styles["body"]),
        Paragraph(f"<b>Address:</b> {part.custodian_address}", styles["body"]),
        Spacer(1, 3 * mm),
        _device_table(part.device, styles),
        Spacer(1, 4 * mm),
        Paragraph(
            "I declare that the above device was, throughout the material "
            "period, under my lawful control and was operating properly.",
            styles["body"],
        ),
        Spacer(1, 3 * mm),
        Paragraph(f"<b>Hash value:</b> <font name='Courier'>{part.hash.value}</font>", styles["mono"]),
        Paragraph(_hash_checkboxes(part.hash.algorithm), styles["mono"]),
        Spacer(1, 4 * mm),
        Paragraph(
            f"<b>Signed at:</b> {part.place} &nbsp;&nbsp; "
            f"<b>Date:</b> {part.date} &nbsp;&nbsp; "
            f"<b>Time (IST):</b> {part.time_ist}",
            styles["body"],
        ),
    ]


def _part_b_story(part: CertificatePartB, styles: dict[str, ParagraphStyle]) -> list:
    return [
        Paragraph(f"<b>Name:</b> {part.expert_name}", styles["body"]),
        Paragraph(f"<b>Designation:</b> {part.expert_designation}", styles["body"]),
        Spacer(1, 3 * mm),
        _device_table(part.device, styles),
        Spacer(1, 4 * mm),
        Paragraph(f"<b>Technical statement:</b> {part.technical_statement}", styles["body"]),
        Spacer(1, 3 * mm),
        Paragraph(f"<b>Hash value:</b> <font name='Courier'>{part.hash.value}</font>", styles["mono"]),
        Paragraph(_hash_checkboxes(part.hash.algorithm), styles["mono"]),
        Spacer(1, 4 * mm),
        Paragraph(
            f"<b>Signed at:</b> {part.place} &nbsp;&nbsp; "
            f"<b>Date:</b> {part.date} &nbsp;&nbsp; "
            f"<b>Time (IST):</b> {part.time_ist}",
            styles["body"],
        ),
    ]


def generate_certificate_pdf(certificate: Certificate, dest_path: str | Path) -> Path:
    """Render ``certificate`` as a PDF at ``dest_path``. Raises
    :class:`CertificateError` if ``dest_path`` already exists — a
    certificate is a signed legal document; silently overwriting one that
    already exists is not this function's call to make."""
    dest_path = Path(dest_path)
    if dest_path.exists():
        raise CertificateError(f"{dest_path} already exists")

    styles = _build_styles()
    doc = SimpleDocTemplate(
        str(dest_path), pagesize=A4,
        topMargin=20 * mm, bottomMargin=18 * mm, leftMargin=20 * mm, rightMargin=20 * mm,
    )

    story: list = [
        Paragraph("Certificate under Section 63(4)", styles["title"]),
        Paragraph("Bharatiya Sakshya Adhiniyam, 2023", styles["subtitle"]),
        Spacer(1, 4 * mm),
        Paragraph(f"<b>Case ID:</b> {certificate.case_id}", styles["body"]),
        Paragraph(
            "Part A - Certificate by the Person in Charge of the Device",
            styles["heading"],
        ),
        *_part_a_story(certificate.part_a, styles),
        PageBreak(),
        Paragraph("Part B - Certificate by a Technical Expert", styles["heading"]),
        *_part_b_story(certificate.part_b, styles),
        Spacer(1, 10 * mm),
        Paragraph(_DISCLAIMER_TEXT, styles["small"]),
    ]

    doc.build(story)
    return dest_path
